# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://jefworks.github.io/scw2015
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jean Fan
  url:               https://jef.works
  email:             jeanfan@fas.harvard.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/JEFworks/scw2015


# Conversion
markdown:         redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks",
      "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter:      pygments